apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taa
  name: taa-dpl
  namespace: taa
spec:
  replicas: 5
  selector:
    matchLabels:
      app: taa
  template:
    metadata:
      labels:
        app: taa
      namespace: taa
    spec:
      containers:
      - name: taa-nginx
        image: donsbx/nginx:latest
        imagePullPolicy: IfNotPresent
      - name: taa-php
        image: donsbx/php-fpm:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: taa-cfm
                key: db_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: taa-cfm
                key: db_name
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: taa-cfm
                key: db_user
      
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: taa
spec:
  type: NodePort
  selector:
    app: taa
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 80
      targetPort: 80